uploads = []
outputs = []

[[generated]]
id = "_P_QveRJNirksyFXL_j55"
uri = "file://artifacts/careconnect/src/assets/images/caregiver-1.png"
type = "image"
title = "Elderly care specialist portrait"

[[generated]]
id = "0eLb9B2jI4XYyegemrNOM"
uri = "file://artifacts/careconnect/src/assets/images/caregiver-2.png"
type = "image"
title = "Pediatric nurse portrait"

[[generated]]
id = "QrLMCVvVHIdQaiWBf6YCG"
uri = "file://artifacts/careconnect/src/assets/images/hero-home.png"
type = "image"
title = "indian-caregiver-elderly-hero"

[[generated]]
id = "e5rj_UZXeYrg53Va7VO7d"
uri = "file://artifacts/careconnect/src/assets/images/caregiver-newborn.png"
type = "image"
title = "indian-caregiver-newborn"

[[generated]]
id = "gnIPYwyaUmzKTba9tOVfp"
uri = "file://artifacts/careconnect/src/assets/images/caregiver-childcare.png"
type = "image"
title = "indian-caregiver-childcare"

[[generated]]
id = "XlgdahBB_V6LHAIwgVZd3"
uri = "file://artifacts/careconnect/src/assets/images/category-pet-care.png"
type = "image"
title = "pet care US home"

[[generated]]
id = "kgfD2QNIAljzmo_HnQwq3"
uri = "file://artifacts/careconnect/src/assets/images/category-newborn-care.png"
type = "image"
title = "newborn care US home"

[[generated]]
id = "SqdJkobLqw_lsr_fwYOTx"
uri = "file://artifacts/careconnect/src/assets/images/category-postpartum-care.png"
type = "image"
title = "postpartum care US home"

[[generated]]
id = "T_32h8KU0eprO-i6yYVb8"
uri = "file://artifacts/careconnect/src/assets/images/category-elderly-care.png"
type = "image"
title = "elderly care US home"

[[generated]]
id = "sq4lOPgBfzQyUZYHu5lXQ"
uri = "file://artifacts/careconnect/src/assets/images/category-special-needs-care.png"
type = "image"
title = "special needs care US home"

[[generated]]
id = "xwY5P0X6ZmTNgILhx9gAZ"
uri = "file://artifacts/careconnect/src/assets/images/category-child-care.png"
type = "image"
title = "child care US home"

[[generated]]
id = "vrUazQAzXsvAAA_cDdSM5"
uri = "file://artifacts/careconnect/src/assets/images/category-house-help.png"
type = "image"
title = "house help US home"

[[generated]]
id = "mICwAHo-SWrYOqkIQurYX"
uri = "file://artifacts/careconnect/src/assets/images/category-kitchen-food-help.png"
type = "image"
title = "kitchen food US home"

[[generated]]
id = "vUc6r7O7tVhIFT_ZpxhJE"
uri = "file://artifacts/careconnect/src/assets/images/category-event-support.png"
type = "image"
title = "event support US home"

[[generated]]
id = "2D58D_w_BUH1_9BVBmy5c"
uri = "file://artifacts/careconnect/src/assets/images/category-travel-medical-care.png"
type = "image"
title = "travel medical US neighborhood"
